server:
  port: 8888

spring:
  application:
    name: image-clustering-module

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        default_batch_fetch_size: 20

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

image-cluster:
  lsh:
    numBands: 8
    bandSize: 8
  hammingThreshold: 10